#!/usr/bin/env python3
#
# EPITECH PROJECT, 2020
# 205IQ_2019
# File description:
# 205IQ
#


import sys
import math

def check_for_err():
    halp = open("help", "r")

    if len(sys.argv) > 1 and sys.argv[1] == "-h":
        print(halp.read(), end = '')
        sys.exit(0)
    if len(sys.argv) < 3 or len(sys.argv) > 5:
        print("Flag error. Try -h for more informations.")
        sys.exit(84)
    flag = []
    for i in range(1, len(sys.argv)):
        try:
            flag.append(int(sys.argv[i]))
        except ValueError:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
    return flag

def calc(val):
    print(val)
    return 0

def main():
    x = check_for_err()
    calc(x)

if __name__ == "__main__":
    main()
